default_platform(:ios)

platform :ios do

  desc "🔧 Build and upload to TestFlight (interactive, local use)"
  lane :testflight_release do
    xcversion(version: ENV["XCODE_VERSION"])

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_filepath: "AuthKey.p8"
    )

    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build ios --no-codesign"
    sh "pod install"

    build_app(
      scheme: "Runner",
      export_method: "app-store",
      skip_package_ipa: false,
      silent: false,
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        method: "app-store",
        provisioningProfiles: {
          "org.qubic.wallet" => "Wallet distribution profile"
        },
        manageAppVersionAndBuildNumber: true
      }
    )

    upload_to_testflight
  end

  desc "🤖 CI: Build and upload silently to TestFlight"
  lane :ci_testflight_release do

    xcodes(
      version: ENV["XCODE_VERSION"],
      select_for_current_build_only: true
    )

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: './AuthKey.p8',
      in_house: false
    )

    UI.message("✅ API key authentication succeeded.")

    apps = Spaceship::ConnectAPI::App.all
    UI.message("🔍 Found #{apps.count} app(s) in App Store Connect.")

    #match(type: "appstore")  # Fetch certificates and provisioning profiles from your certificates repo

    match(
      type: "appstore"#,
      #keychain_password: ENV["P12_PASSWORD"]
    )
    
    sh("ls ~/Library/MobileDevice/Provisioning\\ Profiles/")

    # Check if distribution certificate is installed
    # This will return a list of installed certificates for code signing
    result = sh("security find-identity -v -p codesigning")
  
    # Output the result
    puts "Installed certificates: #{result}"

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      silent: false,
      verbose: ture
      #xcargs: "-allowProvisioningUpdates",
      #export_options: {
      #  signingStyle: "automatic",
      #  manageAppVersionAndBuildNumber: true
     # }
    )
    
     #build_app(
      # scheme: "Runner",
       #export_method: "app-store",
       #c#onfiguration: "Release",   # <- FORCE Release build
       #skip_package_ipa: false,
       #silent: false,
       #clean: true,
       #xcargs: "-allowProvisioningUpdates",
       #export_options: {
         #signingStyle: "automatic",
         #method: "app-store",
         #provisioningProfiles: {
          # "org.qubic.wallet" => "Wallet distribution profile"
        # },
      #   manageAppVersionAndBuildNumber: true
      # }
     #)

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end

end