default_platform(:ios)

platform :ios do

  desc "🔧 Build and upload to TestFlight (interactive, local use)"
  lane :testflight_release do
    xcversion(version: ENV["XCODE_VERSION"])

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_filepath: "AuthKey.p8"
    )

    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build ios --no-codesign"
    sh "pod install"

    build_app(
      scheme: "Runner",
      export_method: "app-store",
      skip_package_ipa: false,
      silent: false,
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        method: "app-store",
        provisioningProfiles: {
          "org.qubic.wallet" => "Wallet distribution profile"
        },
        manageAppVersionAndBuildNumber: true
      }
    )

    upload_to_testflight
  end

  desc "🤖 CI: Build and upload silently to TestFlight"
  lane :ci_testflight_release do

    create_keychain(
      name: "ci_temp_keychain",
      password: ENV['TEMP_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    xcodes(
      version: ENV["XCODE_VERSION"],
      select_for_current_build_only: true
    )

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: './AuthKey.p8',
      in_house: false
    )

    match(
      type: "appstore",
      keychain_name: "ci_temp_keychain", # Specify the keychain to use
      keychain_password: ENV['TEMP_KEYCHAIN_PASSWORD']# Password for the keychain
    )

    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    # Build the app using build_app (this will use the incremented build number)
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      silent: false,
      verbose: true
      #xcargs: "-allowProvisioningUpdates",
      #export_options: {
      #  signingStyle: "automatic",
      #  manageAppVersionAndBuildNumber: true
     # }
    )
    
     #build_app(
      # scheme: "Runner",
       #export_method: "app-store",
       #c#onfiguration: "Release",   # <- FORCE Release build
       #skip_package_ipa: false,
       #silent: false,
       #clean: true,
       #xcargs: "-allowProvisioningUpdates",
       #export_options: {
         #signingStyle: "automatic",
         #method: "app-store",
         #provisioningProfiles: {
          # "org.qubic.wallet" => "Wallet distribution profile"
        # },
      #   manageAppVersionAndBuildNumber: true
      # }
     #)

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )

    # Clean up keychain (optional but good practice)
    delete_keychain(
      name: "ci_temp_keychain"
    )
    
  end

end