name: Commit Message Lint

on:
  push:
    branches:
      #- test/workflow  to remove after testing is ok
      - main
      - dev
      - release/*
      - hotfix/*

  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true
          configFile: ""
