name: Build and Upload APK to Firebase App Distribution

on:
  push:
    branches:
      - test/workflow # to remove after testing is ok
      - main
      - develop
      - release/*
      - hotfix/*

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 📶 Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: 📅 Cache Flutter pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate using Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > "${{ github.workspace }}/firebase-key.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "Internal"
